### ISSUE TITLE
Backend o zona de gestión

### ISSUE THREAD

**Issue by luisprmat** [MinTIC-Group-107/semana-4-107#2]
El **backend** o la zona de gestión, deberá contar con la **administración de los servicios** que se van a visualizar en el sitio web principal o *Portafolio de Servicios*

>  Los nombres de las rutas, componentes y demás aspectos técnicos están definidos en la sección requisitos
obligatorios estructura backend.

El backend implementará el módulo de autenticación realizado en la *semana 3* para validar los **usuarios** y sus **roles**, la zona de administración debe contar inicialmente con la gestión o CRUD de **Artículos** y **Categorías** (como dos elementos de nombre genérico independiente del servicios que se vaya a implementar) y posteriormente se implementará la **gestión de
usuarios** allí mismo.

Para el manejo de rutas, se debe implementar el **router-view** con el fin de sacar provecho del poder de Vue y su característica de SPA.

El **back** deberá proveer una API que permitirá realizar las diferentes peticiones a sus componentes desde el landing page.

#### Login endpoint

Se debe contar un una ruta por medio de método post para el inicio de sesión de la siguiente manera:

```js
'/api/usuario/login'
```
cuando esta ruta es consumida desde el frontend la *api* debe responder en tres casos diferentes:

- Cuando el usuario se loguea exitosamente ,debe responder con un status **200** y
propiedad tokenReturn de la siguiente manera:

```js
res.status(200).json({ user, tokenReturn });
```
- El usuario no existe en la bases de dato, debe responder con un status **404** de la siguiente manera:

```js
res.status(404);
```
esta respuesta se puede complementar con un mensaje como por ejemplo:
```js
res.status(404).send('User Not Found.');
```
- El usuario ingresa una contraseña inválida, debe responder con un status **401** de la siguiente manera:
```js
res.status(401);
```
esta respuesta se puede complementar con un mensaje y propiedades dependiendo de lo que espera recibir en el fontend como por ejemplo:
```js
res.status(401).send({
  auth: false,
  accessToken: null,
  reason: "Invalid Password!"
});
```
#### Categorías Endpoints:

 - Listas de categoría:
```js
'/api/categoria/list'
```
cuando la solicitud se procesa correctamente el sistema deberá responder con un status **200**:
```js
res.status(200)
```
- Agregar una nueva categoría
```js
'/api/categoria/add'
```
cuando la solicitud se procesa correctamente el sistema deberá responder con un status **200**:
```js
res.status(200)
```

- Update categoría
```js
'/api/categoria/update'
```
cuando la solicitud se procesa correctamente el sistema deberá responder con un status **200**:
```js
res.status(200)
```
- Activar estado de la categoría:
```js
'/api/categoria/activate'
```
cuando la solicitud se procesa correctamente el sistema deberá responder con un status **200**:
```js
res.status(200)
```
- Desactivar estado de la categoría:
```js
'/api/categoria/deactivate'
```
cuando la solicitud se procesa correctamente el sistema deberá responder con un status **200**:
```js
res.status(200)
```
#### Artículos Endpoints:

> Las rutas de los artículos tienen la misma estructura de las de categorías, solamente debemos cambiar en las rutas anteriores la palabra **categoria** por **articulo**

> **Nota:** es obligatorio crear las rutas con estas características con el fin que el sistema ejecute satisfactoriamente las pruebas unitarias, obtener la calificación de cada grupo sin ningún problema.

**Comment by Manuel-2011** [comment]
Muchas gracias Luis. Está muy bien documentado todo lo que tendríamos que hacer.

**Comment by Manuel-2011** [comment]
Solo me parece que deberíamos dividir más las tareas para poder asignarles responsable.

**Comment by luisprmat** [comment]
Por supuesto que se pueden dividir las tareas, pero igual esta una tarea general que puede tener varios contribuyentes

**Comment by Manuel-2011** [comment]
> Por supuesto que se pueden dividir las tareas, pero igual esta una tarea general que puede tener varios contribuyentes

Listo Luis, cree un issue aparte de la tarea en la que voy a trabajar que son las apis de las categorías. Traté de dejarla bien documentada y utilicé el markdown como nos recomendaste.

**Comment by luisprmat** [comment]
Si, muy bien, ahí podemos seguir desglosando el proyecto

**Comment by luisprmat** [comment]
Finalizado
