### ISSUE TITLE
Crear modelo del artículo

### ISSUE THREAD

**Issue by Manuel-2011** [MinTIC-Group-107/semana-4-107#7]
# Tabla artículos
La tabla artículos se usará para almacenar todas los artículos que estarán disponibles y serán ofrecidos por la empresa.

## Campos
* id (obligatorio)(integer): id para almacenar el artículo en la tabla.
* codigo (obligatorio)(string): código único del artículo.
* nombre (obligatorio)(string): nombre del artículo.
* descripcion (string): descripción del artículo.
* estado (obligatorio)(integer): solo se acepta 1 o 0. 1 representando si el artículo está activo y 0 si está inactivo.
* categoriaId (obligatorio)(integer): id de la categoría a la que pertenece el artículo.

**Comment by luisprmat** [comment]
Finished
